<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Check_SeleccionaParaPagar</name>
   <tag></tag>
   <elementGuidId>7f8df6f8-6e1a-44f7-9b63-da5be560feeb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;ctl00_cphPrincipal_gveFacturas_ctl02_chkSeleccionar&quot;)[count(. | //*[@id = 'ctl00_cphPrincipal_gveFacturas_ctl02_chkSeleccionar' and @type = 'checkbox' and @name = 'Check_SeleccionaParaPagar' and @onclick = concat('AgregarFacturaCarritoPagos(' , &quot;'&quot; , 'ctl00_cphPrincipal_gveFacturas_ctl02_chkSeleccionar' , &quot;'&quot; , ',' , &quot;'&quot; , '14352' , &quot;'&quot; , '); SeleccionarTodos(false);')]) = count(//*[@id = 'ctl00_cphPrincipal_gveFacturas_ctl02_chkSeleccionar' and @type = 'checkbox' and @name = 'Check_SeleccionaParaPagar' and @onclick = concat('AgregarFacturaCarritoPagos(' , &quot;'&quot; , 'ctl00_cphPrincipal_gveFacturas_ctl02_chkSeleccionar' , &quot;'&quot; , ',' , &quot;'&quot; , '14352' , &quot;'&quot; , '); SeleccionarTodos(false);')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_cphPrincipal_gveFacturas_ctl02_chkSeleccionar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_cphPrincipal_gveFacturas_ctl02_chkSeleccionar</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Check_SeleccionaParaPagar</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>AgregarFacturaCarritoPagos('ctl00_cphPrincipal_gveFacturas_ctl02_chkSeleccionar','14352'); SeleccionarTodos(false);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_cphPrincipal_gveFacturas_ctl02_chkSeleccionar&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_cphPrincipal_gveFacturas_ctl02_chkSeleccionar']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_cphPrincipal_gveFacturas']/tbody/tr[2]/td[8]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/input</value>
   </webElementXpaths>
</WebElementEntity>
